name: Deploy to Minikube (Local Runner)

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run PowerShell Script via CMD
        shell: cmd
        run: |
          call powershell.exe -NoProfile -ExecutionPolicy Bypass -File deploy-local.ps1
