name: Manual Deploy (Clean — No Checkout)

on:
  push:
    branches: [ main ]

permissions:
  contents: none  # 💥 disables default checkout step

jobs:
  deploy:
    runs-on: [self-hosted, windows]

    defaults:
      run:
        shell: powershell

    steps:
      - name: Manual Git Clone & Deploy
        run: |
          $repoPath = "E:/gitactions/actions-runner/_work/helm-nginx-deploy/helm-nginx-deploy"

          # Trust this directory for Git
          git config --global --add safe.directory $repoPath

          # Clean up any previous repo
          if (Test-Path $repoPath) {
            Remove-Item -Recurse -Force $repoPath
          }

          # Clone your GitHub repo
          git clone https://github.com/rsandeep45/helm-nginx-deploy.git $repoPath

          # Run your deploy script
          Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
          cd $repoPath
          .\deploy-local.ps1
