name: Deploy to Minikube

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Minikube
        run: |
          ./deploy-local.ps1
