name: Deploy to Minikube (Local Runner)

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run PowerShell Deployment Script
        run: |
          Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
          .\deploy-local.ps1
        shell: powershell
